### ISSUE TITLE
Azure UI - How to control order of nodes?

### ISSUE THREAD

**Issue by philliphoff** [Microsoft/vscode-azuretools#101]
It looks like the ordering of nodes is based on each's `label` property (i.e. the nodes are in alphabetical order).  If some nodes have indicators in their label (e.g. a `*` as a prefix to indicate selected), currently the node ordering changes as the indicators change, which may be confusing.

Is there a way to keep the nodes in a specific order irrespective of their `label`?

**Comment by EricJizbaMSFT** [comment]
@philliphoff just curious what you're using the ui package for? Are you creating a new extension for VS Code?

In addition, I'm not sure what you mean by "selected". Could you give more detail on why it would have a `*` prefix?

**Comment by philliphoff** [comment]
@EricJizbaMSFT Just a little prototype of something related to the VS tooling I've been working on.  Happy to show you a demo if you want to stop by.

@StephenWeatherford No, sorry, I should have been more clear.  This is strictly about wanting to control the order of the nodes (somewhat) independently of the content of their labels.

A number of CLIs have a concept of an ambient "selected" context (e.g. the Azure CLI with subscriptions, the Kubernetes CLI with clusters, etc.).  If I used a `*`prefix in a label of a node to indicate that it was the currently selected context, VS Code would suddenly shuffle that node to the top of its parent (as the `*` prefix causes the node to sort "higher").  The effect is a little jarring, so I'd like to keep the nodes in the same order regardless of which node has the `*` prefix.

(You could argue that it might be better to use the node icon to indicate selection, and I'd agree, but not being a graphic design artist, a `*` was going to be as good as it gets until I could beg UX to draw me a custom icon.)

#103 is the PR, if you want to see exactly what I'm proposing.

**Comment by EricJizbaMSFT** [comment]
Yeah I'm honestly not sure how I feel about a star at the beginning of the the label to indicate 'selected', but I can totally get on board with the main issue at hand (to allow custom sorting of nodes).

**Comment by philliphoff** [comment]
(The `*` prefix actually mimics what's displayed when using the CLI command to list the items, so it's at least consistent until I get a real UX resource.)
