### ISSUE TITLE
Separate UI utils from Azure specific code in UI package

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azuretools#1051]
We want to move anything from the ui package that is Azure-specific into a new package. So far my best idea for a name is `vscode-azureutils` but I'm not 100% sold on it yet.

**Comment by wwlorey** [comment]
Maybe we call it `vscode-azuretools`? 😜

**Comment by bwateratmsft** [comment]
My vote is for `vscode-azureextensionazuretools365forbusiness`

**Comment by philliphoff** [comment]
I like the idea of an entire rename; we already have decidedly non-Azure extensions that rely on the UI bits in `vscode-azureextensionui`.

That said, VS Code proper may prefer us no use such a generic name as `vscode-extension-xxx`, as the UI bits use a pattern/style that comes from our larger group, and not VS Code itself.

**Comment by bwateratmsft** [comment]
- `vscode-azext-utils`
- `vscode-azext-azureutils`
?

**Comment by alexweininger** [comment]
> * `@microsoft/vscode-azext-utils`
> * `@microsoft/vscode-azext-azureutils`

We've decided to go with these names as a team. 🚀

**Comment by alexweininger** [comment]
Closed in #1054
