### ISSUE TITLE
Publish packages under the @microsoft scope

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azuretools#1052]
Hoping to make this change together with #1051 

- [x] utils → [@microsoft/vscode-azext-utils](https://www.npmjs.com/package/@microsoft/vscode-azext-utils)
- [x] azure → [@microsoft/vscode-azext-azureutils](https://www.npmjs.com/package/@microsoft/vscode-azext-azureutils)
- [x] appservice → [@microsoft/vscode-azext-azureappservice](https://www.npmjs.com/package/@microsoft/vscode-azext-azureappservice)
- [x] dev
- [x] ui (going to deprecate it so not sure if we need to move)
- [ ] kudu
- [ ] database (also unsure of where we are with this package)

**Comment by bwateratmsft** [comment]
Can we mark this done or do we want to get a few more of them under @microsoft? e.g. dev, appservice, etc.

**Comment by alexweininger** [comment]
> Can we mark this done or do we want to get a few more of them under @microsoft? e.g. dev, appservice, etc.

Sounds good, I added a task list.

**Comment by bwateratmsft** [comment]
I think the `ui` folder should probably just get deleted. If we need to create a servicing update for some reason we can go back to a Git tag. If we keep the folder it will just continually generate CG alerts.

**Comment by nturinski** [comment]
> I think the `ui` folder should probably just get deleted. If we need to create a servicing update for some reason we can go back to a Git tag. If we keep the folder it will just continually generate CG alerts.

Yeah, I think we may as well.  Since the package exist in npm, it's not like deleting the folder is going to break users who happen to be consuming.

**Comment by alexweininger** [comment]
I'm always down for some deleting! I'll get on it 🏃‍♂️

**Comment by alexweininger** [comment]
Closing as we've done the main ones
