### ISSUE TITLE
Don't double export from the split UI packages

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azuretools#1073]
I noticed this when working on migrating the storage extension to use the split packages. We can easily work around it for now but long term it's something we should fix.

<img width="834" alt="Screen Shot 2022-02-14 at 2 23 36 PM" src="https://user-images.githubusercontent.com/22795803/153958725-9ecded8e-8a0b-4bc5-92fd-7ee0a4eb4249.png">

**Comment by bwateratmsft** [comment]
Sounds good. I don't think any of those things have actual Azure dependencies so we should be able to include them only in `@microsoft/vscode-azext-utils`.
