### ISSUE TITLE
Updates to utils and azureutils for unified

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azuretools#1096]
List of updates and additions needed to the utils/azureutils packages for the unified extensions. We can add more things as we go.

- [ ] fix `showTreeItemPicker` #1095 
- [x] `getExtensionApi` utility 
- [x] expose `refreshUIOnly` on AzExtTreeDataProvider
- [ ] `createTreeItemsWithErrorHandling` utility

**Comment by bwateratmsft** [comment]
@alexweininger is this closeable now?

**Comment by alexweininger** [comment]
> @alexweininger is this closeable now?

Yep
