### ISSUE TITLE
Deprecation warning for dependencies of `@microsoft/vscode-azext-azureutils`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#1123]
The following 1.x.x packages are all deprecated and need to be upgraded to 2.x.x versions:
- `@azure/arm-resources-subscriptions`
- `@azure/arm-resources-profile-2020-09-01-hybrid`
- `@azure/arm-storage-profile-2020-09-01-hybrid`

**Comment by alexweininger** [comment]
Why do we need these `2020-09-01-hybrid` versions of the SDK? @nturinski

**Comment by bwateratmsft** [comment]
The only references are in https://github.com/microsoft/vscode-azuretools/blob/main/azure/src/clients.ts. Something to do with hybrid cloud? Maybe the T2 packages already cover this?

**Comment by bwateratmsft** [comment]
Duping to #1178. I forgot I'd opened this.
