### ISSUE TITLE
Add link to student account creation

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azuretools#1155]
"Create a free student account..."

It would be awesome to have a custom icon for this if possible and I'll get the link for this soon.

**Comment by GeekTrainer** [comment]
I am efforting tracking down an icon

**Comment by fiveisprime** [comment]
We'll use this one[.](https://iconcloud.design/search/learn/6c47afe3a-c4094e9ea)

![image](https://user-images.githubusercontent.com/1186948/168145781-5573bb32-1e87-4787-91c0-cfe0290c9cd1.png)

**Comment by fiveisprime** [comment]
One more thing, can you remove the "free" from the first option to create an Azure account?

**Comment by nturinski** [comment]
> One more thing, can you remove the "free" from the first option to create an Azure account?

So it just says "Create an Azure Account..."?

**Comment by GeekTrainer** [comment]
One last last little thing - can you remove the **en-us** from the link so it'll choose the appropriate language for the user?

**Comment by fiveisprime** [comment]
Yeah, I saw the screenshot and you're good 😂
