### ISSUE TITLE
Update to Node v16

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#1181]
The packages here can/should be updated to Node v16.

- [x] Update build to Node 16 (#1189)
- [ ] Remove `uuid` (#1194)

**Comment by alexweininger** [comment]
We now use Node v16 in the pipelines https://github.com/microsoft/vscode-azuretools/pull/1189, what else is there to do?

**Comment by bwateratmsft** [comment]
Looks like we're still using `uuid` in many places, so that's one thing that we can clean up.

**Comment by bwateratmsft** [comment]
Some dependencies still use it but that's beyond our control.
