### ISSUE TITLE
Replace `glob-gitignore` with `globby`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#1209]
The AppService package uses `globby` and `glob-gitignore`. `globby` can already do everything we need so we should remove `glob-gitignore`.

**Comment by alexweininger** [comment]
Ugh, globby has changed to ESM so we can't use the latest version. It wouldn't be a big deal but the newer versions include a really nice `ignoreFiles` option, which allows specifying custom `.ignore` files (ex: `.funcignore`).

Is there any way for us to consume an ESM package...?

**Comment by bwateratmsft** [comment]
Not that I know of but that would be really nice...

Can we use an older version of `globby` that isn't esm-only?

**Comment by alexweininger** [comment]
> Not that I know of but that would be really nice...
> 
> Can we use an older version of `globby` that isn't esm-only?

Yeah that's what I'll do. We'll just miss out on that nice feature.
