### ISSUE TITLE
Should the wizard show "(Step 1/5)"?

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azuretools#122]
I removed that functionality when I refactored the wizard in this PR: https://github.com/Microsoft/vscode-azuretools/pull/119 because it didn't seem worth the work at the time, but I'm open to re-implementing it if people liked it.

My problems with the previous implementation:
1. The numbers weren't necessarily consistent or accurate. For example, the 'createWebApp' wizard can show up in the middle of other wizards (like when you deploy), so step 1/5 in that wizard might actually be step 3/7 total
1. We have problems with longer placeholders getting cut-off and until VS Code fixes that issue I'm not sure the step count was the most important information to display

**Comment by StephenWeatherford** [comment]
Agreed if it's re-implemented the steps must be done properly. Not sure it's a high priority, though.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of feedback and the cost of "fixing" this isn't worth the benefit
