### ISSUE TITLE
Update link for student account creation

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/vscode-azuretools#1224]
Although there is an existing link for students (see #1155), we found that the tracking ID is not right and will not produce data in our dashboards. 

The new ID we'd like to use is `academic-74260-alfredodeza`. The full link would then need to be updated to:

https://azure.microsoft.com/free/students/?WT.mc_id=academic-74260-alfredodeza

**Comment by nturinski** [comment]
Thanks for letting us know. We've updated the url with the new ID.

**Comment by alfredodeza** [comment]
This is tremendous @nturinski ! Thanks so much for taking care of this so quickly 🚀
