### ISSUE TITLE
Not able to send telemetry related to subscription Id

### ISSUE THREAD

**Issue by Shruti-MS** [microsoft/vscode-azuretools#1347]
I have a scenario where I need to add subscriptionId in telemetry.
Here is the example code:- This is code that opens a subscription from vscode in Azure portal. I need to send telemetry for the subscriptionId opened using this cmd.

When I set telemetry property to subscriptionId of the node it gets masked. How can I unmasked this to send it in telemetry.

export async function openInPortal(context: IActionContext, node: AzExtTreeItem): Promise<void> {
    const subscriptionId = node.subscription.subscriptionId;
    context.telemetry.properties.subscriptionId = subscriptionId;
    uiOpenInPortal(node, nonNullProp(node, 'id'));
}

Telemetry logged as properties={"isActivationEvent":"false","lastStep":"","result":"Succeeded","stack":"","error":"","errorMessage":{},"treeItemSource":"command",**"subscriptionId":"---"},** measures={"duration":12.872}

I have also set **context.telemetry.suppressMaskLabel =true** but not works.

I want to ask is it not possible to send subscriptionId in telemetry without masking?

Thanks

**Comment by bwateratmsft** [comment]
@Shruti-MS does your extension use the Azure Account extension to authenticate? Azure Account extension telemetry includes the subscription IDs, and you could correlate to machine IDs. It's not the most convenient, but it's probably easier than going through the necessary privacy reviews and GDPR classifications of doing it yourself.

**Comment by Shruti-MS** [comment]
Thanks. Yes we are using Azure Account Extension to authenticate. We will leverage Azure Account for telemetry.
