### ISSUE TITLE
Configure webpack config to handle "webworker" target

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azuretools#1353]
I'm using [Gitlens](https://github.com/gitkraken/vscode-gitlens/blob/8a712cb4314973644ae3e09073222387baa3681c/webpack.config.js) as an example of how we could set up webpack config. They currently return an array of configs which I'm not entirely sure if that's what we want to adopt as well.

**Comment by alexweininger** [comment]
Check out what vscode-python does as well. Looks like they just have separate webpack config files for each target. Their webpack configs might be easier to copy since they don't have webviews like GitLens does (that I know of).

https://github.com/microsoft/vscode-python/tree/main/build/webpack
