### ISSUE TITLE
Migrate off `@azure/ms-rest-js`

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode-azuretools#1473]
It looks that old version of autorest typescript generator was used to generate code that depends on `@azure/ms-rest-js`? Please consider moving to use latest autorest.typescript code generator as `@azure/ms-rest-js` is no longer actively maintained.  

Free free to reach out if you have any questions.

**Comment by bwateratmsft** [comment]
The "kudu" package in this repository is dead and just awaiting removal. The "dev" package still depends on `@azure/ms-rest-js` and some other Track 1 packages, but they are treated as dev-only packages in what is released, so `@azure/ms-rest-js` will no longer be in bundles shipped to customers. However, we should proceed with removing it entirely from these two remaining places.
