### ISSUE TITLE
Confirmation dialogs should be modal

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azuretools#151]
This is a general trend in our extensions, so I'm filing an issue in the tools repo for further discussion. We always use the standard VS Code notifications which used to be very noticeable, but the new notifications are in the bottom right corner and are easy to miss. I think that's fine for a lot of scenarios, but not when we're asking for confirmation for things like deploying or deleting. I think we should use modal dialogs that are very noticeable and force the user to answer right away. VS Code does this in several scenarios, for example:
![screen shot 2018-04-09 at 10 51 42 am](https://user-images.githubusercontent.com/11282622/38513815-39b4be62-3be4-11e8-8d75-7c83ab8f44b2.png)

**Comment by fiveisprime** [comment]
Agreed. This is a solid idea.

How much control is there over the buttons? Is it possible to include the "No and don't warn again" option?

**Comment by StephenWeatherford** [comment]
Agreed

**Comment by EricJizbaMSFT** [comment]
Yes we have control over the buttons
![screen shot 2018-04-09 at 1 37 42 pm](https://user-images.githubusercontent.com/11282622/38521674-3d36a23c-3bfb-11e8-8ded-ba41b605ee05.png)
