### ISSUE TITLE
Deployment broken, if .funcignore contains empty lines

### ISSUE THREAD

**Issue by nikolaiessel** [microsoft/vscode-azuretools#1519]
If I try to deploy my azure function via VSC extension, the ZIP-File is broken:

![image](https://github.com/microsoft/vscode-azuretools/assets/12515305/1c287acf-e04a-49aa-b407-3e6aade27173)

This is caused by the getFilesFromGitignore function in [runWithZipStream](https://github.com/microsoft/vscode-azuretools/blob/main/appservice/src/deploy/runWithZipStream.ts). 
My project contains a **.funcignore** file with blank lines (e.g. last line of file) and therefor the `ignore` array variable - which is created inside the getFilesFromGitignore function - contains empty string elements.
These seems to break the globby call (which was introduced as [glob-gitignore replacement](https://github.com/microsoft/vscode-azuretools/commit/5755299133dd762b82a61aba7e15549a8f834d24#diff-4687132758bf0251f89fb7089a9b97ac1a8e7511b49f9310454da7be91874edf))

**Comment by alexweininger** [comment]
Thanks for the detailed description and investigation! I've opened #1523 to fix this issue.
