### ISSUE TITLE
Expected to find a single "csproj" file in folder

### ISSUE THREAD

**Issue by doronguttman** [Microsoft/vscode-azuretools#164]
Repro steps:

1. used CLI to do `func init Office365Functions`
2. `cd Office365Functions`
3. `code .`
4. when code started got the prompt for "Detected an Azure Functions Project folder, that may have been created outside of VS Code. Initialize for optimal use with VS Code?"
5. hit `Yes`
6. from the command bar drop down selected `c#`

Action: azureFunctions.validateFunctionProjects
Error type: Error
Error Message: Expected to find a single "csproj" file in folder "Office365Functions", but found zero or multiple instead.

Version: Unknown
OS: win32

**Comment by EricJizbaMSFT** [comment]
Thanks for reporting. As a workaround, you can create a C# project directly in VS Code: https://github.com/Microsoft/vscode-azurefunctions#create-new-project

That being said, what would be your ideal experience for the scenario above? We check the csproj file for the targetFrameworkVersion, which affects your experience in VS Code (for example, creating an HttpTrigger for .NET Core is different than creating one for .NET Framework).

For example, would you like us to create a csproj file for you? AFAIK - the func cli only supports C# _Scripts_, so you would never get a csproj file from `func init` or `func new`

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
