### ISSUE TITLE
Can't see subscriptions where I'm invited into !!! ASAP

### ISSUE THREAD

**Issue by erikpa1** [microsoft/vscode-azuretools#1792]
Hi, In Azure Tools I can't see subscriptions of organizations where I'm into.

Before I needed to log in to azure sign in to their tenant, and open Visual Studio code, and then they were there, but today, it's dead, nothing helps, I tried az login --tenant xxx , I tried restart pc, uninstal plugin, set client directory as azure startup but nothing helped....

please help ASAP

![image](https://github.com/user-attachments/assets/4775cc19-1cf8-4fa8-bf35-b13e3f472dc8)

**Comment by alexweininger** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureresourcegroups/issues/925
