### ISSUE TITLE
getSubscriptions() throws if user has signed in to two accounts

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azuretools#1809]
1) run the script from https://github.com/Azure/bicep/pull/15403#issuecomment-2448473532 to install a version of the Bicep extension that uses the new @microsoft/vscode-azext-azureauth functionality
2) Using azureResourceGroups.login, log in to two different accounts in Azure.  (Note: I did this because I was testing a different Azure account, but it wasn't obvious how to sign out of the first one, I assumed this would do it.)
3) Create a new main.bicep file and save it with:
```bicep
resource storageaccount 'Microsoft.Storage/storageAccounts@2021-02-01' = {
  name: 'name'
  location: 'westus3'
  kind: 'StorageV2'
  sku: {
    name: 'Premium_LRS'
  }
}
```
4) in the editor's context menu for main.bicep, click "Deploy Bicep File..."
5) Click enter for default deployment name
!) Next you should see a picklist of subscriptions, but you will instead see ,in the Output window, under "Bicep Operations", this error:
> 1:57:16 PM: Deployment failed for c:\Users\stephwe\Downloads\main.bicep. You are not signed in to an Azure account. Please sign in.
EXPECTED: should work

More details:
![Image](https://github.com/user-attachments/assets/edbb2fce-6996-41e0-a7fa-6202252ba7e6)
We call isSignedIn(), which finds that there's a session open for the first account and returns true.  So then we call getSubscriptions(), which calls getTenants() on each account.  The second getTenants() call throws because the second account doesn't have an open session:

![Image](https://github.com/user-attachments/assets/6e847c23-0765-48d3-b7ad-07d5ee17ea83)
```
getSubscriptionClient (vscode-bicep\node_modules\@microsoft\vscode-azext-azureauth\out\src\VSCodeAzureSubscriptionProvider.js:297)
getTenants (vscode-bicep\node_modules\@microsoft\vscode-azext-azureauth\out\src\VSCodeAzureSubscriptionProvider.js:80)
getSubscriptions (vscode-bicep\node_modules\@microsoft\vscode-azext-azureauth\out\src\VSCodeAzureSubscriptionProvider.js:138)
```

**Comment by StephenWeatherford** [comment]
@alexweininger What are the plans for this bug?  I need to know if I should do a work-around for our next release, which has the change to the new API.  Thanks.

**Comment by alexweininger** [comment]
@StephenWeatherford I will try to have an answer by tomorrow morning 😄. When are you hoping to release?

**Comment by alexweininger** [comment]
@StephenWeatherford what version of the auth package are you using? v3.0.0 included https://github.com/microsoft/vscode-azuretools/pull/1789 and I think that should prevent this issue.

**Comment by StephenWeatherford** [comment]
Unfortunately not.
