### ISSUE TITLE
Subscriptions list is empty for all Deploy commands until that extension's view has been opened

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azuretools#186]
This is new behavior since the adoption of the Azure view

1) Install Functions app (or storage with static website support or appservice)
2) Right-click a folder in the project, -> "Deploy to Function App"
!) When "Select a Subscription" comes up, it's empty

Work-around: Open Azure view, open Functions view, try again

**Comment by nturinski** [comment]
Is there anyway to run commands from the extension before it is activated?

**Comment by StephenWeatherford** [comment]
Yes, that's what the activationEvents list in package.json is for.  The app gets activated correctly when the command is run, but the subscription picker remains empty and therefore useless.

**Comment by StephenWeatherford** [comment]
This is the same for all extensions - e.g. deploy to static website in storage extension.
