### ISSUE TITLE
Support other app service runtimes

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azuretools#20]
Requires an additional step to keep the runtime list from getting out of control - select the runtime then the version.

*runtime (nodejs, java) -> version (nodejs 8.1)*

**Comment by EricJizbaMSFT** [comment]
Moving this issue to the app service repo https://github.com/Microsoft/vscode-azureappservice/issues/299

(That way we can track it in the milestones with all other features)
