### ISSUE TITLE
Update UA string for SDK

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azuretools#200]
I'm not sure if this is the correct repo for this...

The ms-rest module has an method to update the UA String for tracking the origin of requests on the server side. We need to set this for the extensions so we can log requests from VS Code.

```js
client.addUserAgentInfo(`vscode-${package.name}/${package.version}`)
```

**Comment by EricJizbaMSFT** [comment]
Closing this as we now have individual issues in each repo.
