### ISSUE TITLE
Auth behind corporate proxy: Clicking Sign in to Azure does nothing

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azuretools#330]
I'm porting a bug from Cosmos: https://github.com/Microsoft/vscode-cosmosdb/issues/949

Text: 
When clicking the "Sign in to Azure..." it changes to "Waiting for Azure Sign-in..." for a second, then switches back. Nothing else happens and no error message is received. Note that I am behind a corporate proxy which may be causing issues.

**Comment by EricJizbaMSFT** [comment]
@PrashanthCorp It's generally better _not_ to move a user-reported issue to this repo. We regularly triage and track the extension repos, but we don't do that for this repo. Plus the bug might be in the azure-account extension which means this repo wouldn't even be the right place

**Comment by PrashanthCorp** [comment]
It looks like an issue with azure-account's handling of proxy.
