### ISSUE TITLE
zip deploy should warn that it is a destructive action

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azuretools#4]

**Comment by wely** [comment]
totally agreed.

I was one of the victim which my functions within the function app got deleted. And I won't be able to revive it back again :(

**Comment by wely** [comment]
Is the features of warning user got implemented, Eric?

**Comment by fiveisprime** [comment]
@wely this was released in functions@0.1.1 and appservice@0.3.1 🥂
