### ISSUE TITLE
Switch over to azure-sdk-for-js

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azuretools#510]
- [ ] UI (Prashanth)
- [ ]  appservice
- [ ]  kudu

**Comment by formulahendry** [comment]
+1
Want to know the plan of switching over to azure-sdk-to-js

**Comment by EricJizbaMSFT** [comment]
Currently blocked on https://github.com/microsoft/vscode-azure-account/issues/140

**Comment by bwateratmsft** [comment]
This should now be unblocked; https://github.com/microsoft/vscode-azure-account/issues/140 has been "fixed" (it now surfaces both the old and new SDKs at least until people have enough time to move off the old).

**Comment by EricJizbaMSFT** [comment]
@bwateratmsft yeah we really want to move to the new sdks, too 🙂 . Was planning on working on this in the next few weeks

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT That would be awesome. I'm going to try to convince the powers-that-be to let me work on this for Docker as well; I may be able to help here too (no promises!)
