### ISSUE TITLE
[Feature Request][vscode-azureextensionui] Support setting collapsibleState for AzExt***TreeItem

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azuretools#631]
We want to create a AzExtParentTreeItem with Expanded status. 

https://github.com/Microsoft/vscode-azuretools/blob/master/ui/src/treeDataProvider/AzExtParentTreeItem.ts#L29
![image](https://user-images.githubusercontent.com/1050213/69851736-5dcc2400-12bd-11ea-8bf5-65253579fad6.png)

However, the collapsibleState is readonly, and it seems that there is no constructor exposed to pass the collapsibleState.

**Comment by EricJizbaMSFT** [comment]
@formulahendry my team owns several Azure extensions and we mainly created these packages for our own use instead of as an end product per se. We're happy to let other people use these, but we prefer more of a collaborative approach (aka PRs instead of feature requests)
