### ISSUE TITLE
[Question] How to distinguish telemetry from two tree views.

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azuretools#636]
When loading children of Azure Subscriptions, there would be telemetry event like `vsciot-vscode.azure-iot-toolkit/IoTHub.AzureTreeDataProvider.getChildren` with contextValue = `azureextensionui.azureSubscription`.
In actual usage in Azure IoT Hub Toolkit, we have two tree views, want to know whether there is a way to distinguish telemetry from two tree views.
![image](https://user-images.githubusercontent.com/1050213/70420914-b1035b00-1aa3-11ea-96b0-2ebf39a2a8c2.png)

**Comment by EricJizbaMSFT** [comment]
There's nothing by default for the subscription node. Obviously the child resources under a subscription will probably have different context values. The easiest fix is that you can add whatever telemetry you want inside `loadMoreChildrenImpl` on the `context.telemetry.properties` object.

**Comment by formulahendry** [comment]
Got it. Thank you!
