### ISSUE TITLE
Error trying to set output EventHubProperties.PropertyColumns

### ISSUE THREAD

**Issue by leonicolas** [microsoft/vscode-azuretools#638]
Repo steps:
- Open an Output JSON file.
- Add a string value inside the EventHubProperties.PropertyColumns property array.

After insert the fields names into PropertyColumns array the Output is not added anymore to the final deploy JSON.

Action: asa.config.provideCodeLenses
Error type: TypeError
Error Message: Cannot read property 'value' of undefined

Version: Azure Stream Analytics Tools 0.2.0
OS: Windows 10 - 64 bits

**Comment by EricJizbaMSFT** [comment]
@leonicolas what extension for VS Code did you get this error on? I'm not familiar with this scenario and you'd probably have better luck on that extension's repo directly
