### ISSUE TITLE
Lost my Azure Icon on the VSCODE activity bar

### ISSUE THREAD

**Issue by DrYSG** [microsoft/vscode-azuretools#785]
I have been using the VSCODE Azure extensions successfully till yesterday.
Yesterday I changed the Azure account (and it says I a logged in)
I also added the azure machine language extension.

Now, I no longer have the Azure Icon on the Activity bar, and I have no idea where to find the logs that say something is going wrong. I don't get any visible errors, and I have tried reboot, and re-install of each of these extensions:

* Azure Account
* Azure App Service
* Azure Database
* Azure Functions
* Azure Machine Learning
* Azure Resource Manager (ARM) Tools
* Azure Storage

All claim to be the latest versions

----
```
    VSCODE Version: 1.47.3 (user setup)
    Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
    Date: 2020-07-23T13:12:49.994Z
    Electron: 7.3.2
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Windows_NT x64 10.0.18363

```

**Comment by StephenWeatherford** [comment]
I'm not seeing this with the same version (MacOs).  VS Code actually handles displaying the icon, the extensions simply announce its existence in the extension manifests.  My first question would be whether it's there but the icon is invisible.  Have you tried the shortcut (SHIFT+CTRL+A I think, on Mac it's SHIFT+CMD+A)?  And maybe hover the mouse over where the icon should be and see if you get a tooltip?  If not, please report it as a vscode bug (and link to this one).

You could also try seeing if it shows up when you have only Azure Account and one other extension enabled (try a couple different ones), to see if somehow one of them is interferring.

**Comment by DrYSG** [comment]
@StephenWeatherford Your intuition is perfect. It was a hidden icon. Fixed with SHIFT+CTRL+A . I had no idea you could hide them.

**Comment by StephenWeatherford** [comment]
Right-clicking on the panel should allow you to re-show the icon if that's what happened.  Otherwise probably a hiccup of some sort by vscode.
