### ISSUE TITLE
Incorrect telemetry gets logged due to parallel instances

### ISSUE THREAD

**Issue by kanika1894** [microsoft/vscode-azuretools#799]
In the scenario where some API calls are made post a user input, and nothing is there at the user end for interaction, if we start another flow, (say, using Ctrl+Shift+P), a new flow begins and a telemetry log with Result : Succeeded get created even if we cancel or if there comes an error when the flow returns from the API call.

This is a typical behavior when a new flow gets started when something else is happening in the background. At that stage, even pressing Esc isn't considered.

Repro steps (with deploy-to-azure extension) :

Begin an execution flow to deploy a ci/cd pipeline.
In middle of the flow, start a new flow (using Ctrl+SHift+P)post the input of GitHubPat/Azure resource.
At these stages, certain things are happening in the background and no user input is expected.
The observation is whenever the first flow returns, irrespective of it's output, a telemetry log with Result = succeeded gets created.

If the user is beginning a new flow, either previous flow should stop there itself or a new flow shouldn't begin. Due to the parallel instances, this issue seems to be occurring.

**Comment by EricJizbaMSFT** [comment]
@kanika1894 the behavior of telemetry is highly dependent on the authors of the extension itself. I suggest you investigate within the "Deploy to Azure" extension
