### ISSUE TITLE
TypeScript 4 error: accessors overriding properties in AzExt*TreeItem

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#805]
Thanks to a [new error](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#properties-overriding-accessors-and-vice-versa-is-an-error) in TypeScript 4, many errors get thrown when trying to build `vscode-azureextensionui` (or, a consumer of its `TreeView` framework) against TS 4.0.

![image](https://user-images.githubusercontent.com/36966225/94154384-cfc4b980-fe4b-11ea-939f-e72d2dded25b.png)

I think fixing this would require defining these "properties" as abstract, which means consumers would have to implement them (which would make this a breaking change). If they are abstract, the implementer can implement them either as properties or as accessors.

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT I'm happy to help with the fix here. Do you have any thoughts on how to go about it? I think that changing the class declarations to interfaces would work, but my understanding of libraries / `declare` / etc. is not very strong.

**Comment by EricJizbaMSFT** [comment]
Yeah we don't have any immediate plans to upgrade to TypeScript 4, so I probably wouldn't get to this any time soon. You're welcome to take a shot at it and feel free to make breaking changes if necessary

**Comment by bwateratmsft** [comment]
I got started and immediately realized this is going to be a nightmare. There are probably 50+ files in the Docker extension alone that would need changes...

**Comment by bwateratmsft** [comment]
I found a somewhat less-intrusive solution that unblocked Docker without needing changes here: https://github.com/microsoft/vscode-docker/pull/2348

In short, I have intermediate abstract classes that redefine the parent (`AzExtTreeItem`, `AzExtParentTreeItem`) properties as abstracts, allowing inheriting classes to implement the abstract as either a property or an accessor. I don't think that solution is applicable to this repo though.
