### ISSUE TITLE
Update common Azure account icon to match new UX?

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-azuretools#921]
The Azure icon has recently been [updated](https://azure.microsoft.com/en-us/blog/a-fluent-new-look-for-the-azure-icon/). Should the common Azure account icon in [vscode-azureextensionui](https://github.com/microsoft/vscode-azuretools/tree/main/ui) be updated to match?

<img width="220" alt="Screenshot 2021-05-17 at 09 43 47" src="https://user-images.githubusercontent.com/6402946/118526157-cf3ba480-b6f4-11eb-9306-98fb1aa1c6af.png">

> Note: the image is a screenshot of the Docker extension, which uses the common Azure account node from `vscode-azureextensionui`.

**Comment by ejizba** [comment]
@philliphoff any chance you could take care of this? 😊 Docker is the only extension I'm aware of that actually has the Azure icon in the tree

**Comment by philliphoff** [comment]
I'm happy to ask @ucheNkadiCode to get us the new official SVG.  :-)

**Comment by ucheNkadiCode** [comment]
@philliphoff, I've sent over the appropriate files. Let me know if there are any further issues.
