### ISSUE TITLE
UI Windows- Source: Null Extension Description

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azuretools#93]
Does anybody know why this is coming up with the information/warning/error windows?

![image](https://user-images.githubusercontent.com/5290572/36823421-eb111c5c-1cb1-11e8-91b7-2d1d8c0819db.png)

**Comment by StephenWeatherford** [comment]
Just what it says. You pay for the service plan whether it has any app services in it or not. It could probably be phrased better.

Don't know why the null description, is our package.json not correct?

**Comment by EricJizbaMSFT** [comment]
Looks fixed as of today's insiders build. Reopen if you can still repro
![screen shot 2018-03-01 at 10 26 38 am](https://user-images.githubusercontent.com/11282622/36862244-18e2c962-1d3b-11e8-8bd9-31973f8501bd.png)

**Comment by EricJizbaMSFT** [comment]
Okay I think I found the difference. I see "Null Extension Description" from errors displayed from the shared packages, and the correct extension description from errors displayed by the extensions directly

**Comment by EricJizbaMSFT** [comment]
Haven't seen "Null Extension Description" in a really long time (since they first added these notifications) so closing this
