### ISSUE TITLE
Azure nodes can (should?) now use the Azure codicon instead of a custom image

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#978]
A [codicon has been added for Azure](https://code.visualstudio.com/updates/v1_59#_updated-codicons). The `vscode-azureextensionui` package can (and maybe should?) now use this for Azure nodes.

I believe this would raise the minimum required VSCode version to 1.59 though, so this probably shouldn't be done for a while.

**Comment by alexweininger** [comment]
Which nodes can we use this for? The only place that icon is used is for the Activity Bar.

**Comment by bwateratmsft** [comment]
That's exactly where. IIRC it's also bundling the icons in the package.

**Comment by alexweininger** [comment]
Ok, the place we need to change it is in Resource Groups then. Since that's where we register the view containers that use the icon.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/477
